# Generated by Django 3.2.8 on 2021-10-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmark',
            name='total_mark',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='history_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='maths_mark',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='science_mark',
            field=models.IntegerField(),
        ),
    ]
